# docker-compose.yml
vendors:
    image: fix_python2 #fix_python # - for cmake (dlib)
    working_dir: /mnt
    volumes:
      - ./:/mnt
    environment:
      PYTHONUSERBASE: /mnt/vendor
    command: pip install -r requirements.txt --user --upgrade
    #docker-compose run --rm vendors

server:
    image: fix_python2
    working_dir: /mnt
    volumes:
      - ./:/mnt
    ports:
      - '8000:8000'
    links:
      - mysql
    environment:
      PYTHONPATH: src
      PYTHONUSERBASE: /mnt/vendor
    command: python app.py
    #docker-compose up server

mysql:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    #volumes:
    #  - /var/lib/mysql:/var/lib/mysql

pyapp:
    build: .
    ports:
      - 7000

loadbalancer:
    image: 'dockercloud/haproxy:latest'
    links:
      - pyapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    #environment:
    #  VIRTUAL_HOST: 'localhost:7000'
    #docker-compose up -d
    #docker-compose scale pyapp=5
    # docker-compose stop loadbalancer
    # docker-compose rm loadbalancer
    # docker-compose up -d --no-deps loadbalancer

mysql-master:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    volumes:
      - /path/to/mysql-persistence:/bitnami
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
  mysql-slave:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password